-- ---------- roles -----------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_role(auth.uid(), 'admin')
$$;

DROP POLICY IF EXISTS "Users can read their own roles" ON public.user_roles;
CREATE POLICY "Users can read their own roles" ON public.user_roles
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- ---------- shared updated_at trigger --------------------------------------
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- ---------- profile (single row) -------------------------------------------
CREATE TABLE public.profile (
  id integer PRIMARY KEY CHECK (id = 1),
  name text NOT NULL,
  titles text[] NOT NULL DEFAULT '{}',
  tagline text, bio text, about_story text, about_philosophy text,
  location text, email text, phone text, whatsapp text,
  github text, linkedin text, twitter text, discord text,
  resume_url text, avatar_url text DEFAULT '/assets/profile.png',
  available_for_hire boolean NOT NULL DEFAULT true,
  years_experience text DEFAULT '3+',
  happy_clients text DEFAULT '100+',
  projects_completed text DEFAULT '50+',
  satisfaction_rate text DEFAULT '99%',
  meta_title text, meta_description text, meta_keywords text,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.profile TO anon, authenticated;
GRANT INSERT, UPDATE ON public.profile TO authenticated;
GRANT ALL ON public.profile TO service_role;
ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profile is publicly readable" ON public.profile FOR SELECT USING (true);
CREATE POLICY "Admins can update profile" ON public.profile FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can insert profile" ON public.profile FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE TRIGGER profile_touch BEFORE UPDATE ON public.profile FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------- projects -------------------------------------------------------
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL,
  short_description text NOT NULL DEFAULT '',
  full_description text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  gallery_images text[] NOT NULL DEFAULT '{}',
  technologies text[] NOT NULL DEFAULT '{}',
  challenges text, solutions text, outcomes text,
  live_url text, github_url text,
  featured boolean NOT NULL DEFAULT false,
  likes integer NOT NULL DEFAULT 0 CHECK (likes >= 0),
  views integer NOT NULL DEFAULT 0 CHECK (views >= 0),
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX projects_order_idx ON public.projects (order_index, id);
GRANT SELECT ON public.projects TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.projects TO authenticated;
GRANT ALL ON public.projects TO service_role;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Projects are publicly readable" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Admins manage projects insert" ON public.projects FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage projects update" ON public.projects FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage projects delete" ON public.projects FOR DELETE TO authenticated USING (public.is_admin());
CREATE TRIGGER projects_touch BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ---------- skills ---------------------------------------------------------
CREATE TABLE public.skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  level text NOT NULL DEFAULT 'Advanced',
  percentage integer NOT NULL DEFAULT 0 CHECK (percentage BETWEEN 0 AND 100),
  icon text,
  color text DEFAULT 'from-blue-400 to-blue-600',
  featured boolean NOT NULL DEFAULT true,
  years_experience text DEFAULT '2+ yrs',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX skills_order_idx ON public.skills (order_index, id);
GRANT SELECT ON public.skills TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.skills TO authenticated;
GRANT ALL ON public.skills TO service_role;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Skills are publicly readable" ON public.skills FOR SELECT USING (true);
CREATE POLICY "Admins manage skills insert" ON public.skills FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage skills update" ON public.skills FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage skills delete" ON public.skills FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- experiences ----------------------------------------------------
CREATE TABLE public.experiences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL DEFAULT 'work' CHECK (type IN ('work','education')),
  title text NOT NULL,
  company_or_school text NOT NULL,
  location text,
  period text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  achievements text[] NOT NULL DEFAULT '{}',
  technologies text[] NOT NULL DEFAULT '{}',
  icon text DEFAULT '💻',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX experiences_order_idx ON public.experiences (order_index, id);
GRANT SELECT ON public.experiences TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.experiences TO authenticated;
GRANT ALL ON public.experiences TO service_role;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Experiences are publicly readable" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Admins manage experiences insert" ON public.experiences FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage experiences update" ON public.experiences FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage experiences delete" ON public.experiences FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- services -------------------------------------------------------
CREATE TABLE public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  icon text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  features text[] NOT NULL DEFAULT '{}',
  starting_price text,
  timeline_estimate text,
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX services_order_idx ON public.services (order_index, id);
GRANT SELECT ON public.services TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.services TO authenticated;
GRANT ALL ON public.services TO service_role;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Services are publicly readable" ON public.services FOR SELECT USING (true);
CREATE POLICY "Admins manage services insert" ON public.services FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage services update" ON public.services FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage services delete" ON public.services FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- certificates ---------------------------------------------------
CREATE TABLE public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  issuer text NOT NULL,
  year text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  credential_url text, credential_id text, image text,
  color text DEFAULT 'from-blue-400 to-purple-600',
  dark_color text DEFAULT 'from-blue-500 to-purple-700',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX certificates_order_idx ON public.certificates (order_index, id);
GRANT SELECT ON public.certificates TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.certificates TO authenticated;
GRANT ALL ON public.certificates TO service_role;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Certificates are publicly readable" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Admins manage certificates insert" ON public.certificates FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage certificates update" ON public.certificates FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage certificates delete" ON public.certificates FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- testimonials ---------------------------------------------------
CREATE TABLE public.testimonials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text NOT NULL DEFAULT '',
  company text NOT NULL DEFAULT '',
  avatar text,
  rating integer NOT NULL DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  text text NOT NULL,
  project_name text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  is_featured boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX testimonials_status_idx ON public.testimonials (status, id DESC);
GRANT SELECT ON public.testimonials TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.testimonials TO authenticated;
GRANT ALL ON public.testimonials TO service_role;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Approved testimonials are public" ON public.testimonials FOR SELECT USING (status = 'approved');
CREATE POLICY "Admins read all testimonials" ON public.testimonials FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins manage testimonials update" ON public.testimonials FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins manage testimonials delete" ON public.testimonials FOR DELETE TO authenticated USING (public.is_admin());
CREATE POLICY "Admins insert testimonials" ON public.testimonials FOR INSERT TO authenticated WITH CHECK (public.is_admin());

-- ---------- chatbot knowledge ---------------------------------------------
CREATE TABLE public.chatbot_knowledge (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  trigger_keywords text NOT NULL DEFAULT '',
  question text NOT NULL,
  answer text NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX chatbot_knowledge_order_idx ON public.chatbot_knowledge (order_index, id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chatbot_knowledge TO authenticated;
GRANT ALL ON public.chatbot_knowledge TO service_role;
ALTER TABLE public.chatbot_knowledge ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins read knowledge" ON public.chatbot_knowledge FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins insert knowledge" ON public.chatbot_knowledge FOR INSERT TO authenticated WITH CHECK (public.is_admin());
CREATE POLICY "Admins update knowledge" ON public.chatbot_knowledge FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins delete knowledge" ON public.chatbot_knowledge FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- analytics ------------------------------------------------------
CREATE TABLE public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  path text, referrer text, ip_hash text, user_agent text, device_type text,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX analytics_events_type_idx ON public.analytics_events (event_type, created_at DESC);
GRANT SELECT ON public.analytics_events TO authenticated;
GRANT ALL ON public.analytics_events TO service_role;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins read analytics" ON public.analytics_events FOR SELECT TO authenticated USING (public.is_admin());

-- ---------- contact messages ----------------------------------------------
DROP TABLE IF EXISTS public.contact_messages;
CREATE TABLE public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text NOT NULL DEFAULT 'Project Inquiry',
  message text NOT NULL,
  project_type text,
  estimated_budget text,
  source text NOT NULL DEFAULT 'contact_form',
  status text NOT NULL DEFAULT 'unread' CHECK (status IN ('unread','read','starred','replied','archived')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_messages_status_idx ON public.contact_messages (status, id DESC);
GRANT SELECT, UPDATE, DELETE ON public.contact_messages TO authenticated;
GRANT ALL ON public.contact_messages TO service_role;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins read messages" ON public.contact_messages FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "Admins update messages" ON public.contact_messages FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins delete messages" ON public.contact_messages FOR DELETE TO authenticated USING (public.is_admin());

-- ---------- public project engagement counters ----------------------------
CREATE OR REPLACE FUNCTION public.increment_project_view(_project_id bigint)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_views integer;
BEGIN
  UPDATE public.projects SET views = views + 1 WHERE id = _project_id RETURNING views INTO new_views;
  IF new_views IS NULL THEN RAISE EXCEPTION 'Project % not found', _project_id; END IF;
  RETURN new_views;
END $$;

CREATE OR REPLACE FUNCTION public.increment_project_like(_project_id bigint)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_likes integer;
BEGIN
  UPDATE public.projects SET likes = likes + 1 WHERE id = _project_id RETURNING likes INTO new_likes;
  IF new_likes IS NULL THEN RAISE EXCEPTION 'Project % not found', _project_id; END IF;
  RETURN new_likes;
END $$;

REVOKE ALL ON FUNCTION public.increment_project_view(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.increment_project_like(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_project_view(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_project_like(bigint) TO anon, authenticated;

REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.resync_identity(_table text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE seq text;
BEGIN
  IF _table NOT IN ('projects','skills','experiences','services','certificates','testimonials','chatbot_knowledge','contact_messages','analytics_events') THEN
    RAISE EXCEPTION 'Unsupported table %', _table;
  END IF;
  seq := pg_get_serial_sequence('public.' || quote_ident(_table), 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(id) FROM public.%I), 1))', seq, _table);
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.resync_identity(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resync_identity(text) TO service_role;